name: new_todo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3+17

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  get: ^4.6.6
  cloud_firestore: ^5.1.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  # Assets bölümünü aktif hale getirin
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#6200EE"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/logo_light.png
  color_dark: "#121212"
  image_dark: assets/icon/logo_dark.png
  android_12:
    image: assets/icon/logo_light.png
    image_dark: assets/icon/logo_dark.png
