// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Web API Key (if available)
    appId: 'YOUR_WEB_APP_ID', // Web App ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Messaging Sender ID
    projectId: 'todoapp-4f994', // Your Project ID
    authDomain: 'todoapp-4f994.firebaseapp.com', // Auth Domain
    storageBucket: 'todoapp-4f994.appspot.com', // Storage Bucket
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJNSxRW8iVycVexU_zzZRbwT97LDVxuU', // Your Android API Key
    appId: '1:1040199626863:android:a59b0c20ca83e9f0d05d9a', // Your Android App ID
    messagingSenderId: '1040199626863', // Your Messaging Sender ID
    projectId: 'todoapp-4f994', // Your Project ID
    storageBucket: 'todoapp-4f994.appspot.com', // Storage Bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // iOS API Key
    appId: 'YOUR_IOS_APP_ID', // iOS App ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Messaging Sender ID
    projectId: 'todoapp-4f994', // Your Project ID
    storageBucket: 'todoapp-4f994.appspot.com', // Storage Bucket
    iosBundleId: 'com.example.todoTaskApp', // Your iOS Bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // macOS API Key
    appId: 'YOUR_MACOS_APP_ID', // macOS App ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Messaging Sender ID
    projectId: 'todoapp-4f994', // Your Project ID
    storageBucket: 'todoapp-4f994.appspot.com', // Storage Bucket
    iosBundleId: 'com.example.todoTaskApp', // Your macOS Bundle ID
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY', // Windows API Key
    appId: 'YOUR_WINDOWS_APP_ID', // Windows App ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Messaging Sender ID
    projectId: 'todoapp-4f994', // Your Project ID
    authDomain: 'todoapp-4f994.firebaseapp.com', // Auth Domain
    storageBucket: 'todoapp-4f994.appspot.com', // Storage Bucket
  );
}
